server:
  port: 8009
spring:
  application:
    name: base-zipkin-admin
eureka:
  instance:
    lease-expiration-duration-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS